# Generated by Django 3.0.5 on 2020-04-22 10:11
from decimal import Decimal

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations

from accounts.models import AccountCurrencyChoices


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    User = apps.get_model(settings.AUTH_USER_MODEL)
    Account = apps.get_model('accounts', 'Account')
    CustomerAccount = apps.get_model('accounts', 'CustomerAccount')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ca_ct = ContentType.objects.get_for_model(CustomerAccount)

    user = User.objects.using(db_alias).create(
        username='superuser',
        first_name='Fedor',
        last_name='Dostoevsky',
        is_staff=True,
        is_superuser=True,
        password=make_password('123')
    )
    user.save()

    for currency in AccountCurrencyChoices.values:
        a = CustomerAccount.objects.using(db_alias).create(
            owner=user,
            currency=currency,
            balance=Decimal(500),
        )
        Account.objects.filter(
            id=a.account_ptr_id
        ).update(polymorphic_ctype_id=ca_ct)

    user = User.objects.using(db_alias).create(
        username='user2',
        first_name='Alexandr',
        last_name='Green',
    )
    for currency in AccountCurrencyChoices.values:
        a = CustomerAccount.objects.using(db_alias).create(
            owner=user,
            currency=currency,
            balance=Decimal(500),
        )
        Account.objects.filter(
            id=a.account_ptr_id
        ).update(polymorphic_ctype_id=ca_ct)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
