# Generated by Django 3.0.5 on 2020-04-22 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс')),
                ('currency', models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Rub'), ('EUR', 'Eur')], max_length=4, verbose_name='Валюта счёта')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_accounts.account_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name': 'Счёт банка',
                'verbose_name_plural': 'Счёта банка',
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Комиссия')),
                ('new_from_balance', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Новый баланс')),
                ('new_to_balance', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Новый баланс')),
                ('description', models.CharField(max_length=250, verbose_name='Примечание')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Error')], default=0)),
                ('error_msg', models.CharField(max_length=250, verbose_name='Причина отклонения')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_transations', to='accounts.Account', verbose_name='Счет отправитель')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transations', to='accounts.Account', verbose_name='Счет получатель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счёт клиента',
                'verbose_name_plural': 'Счета клиентов',
            },
            bases=('accounts.account',),
        ),
    ]
