# Generated by Django 3.0.5 on 2020-04-23 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_auto_20200422_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
    ]
